# Generated by Django 2.0 on 2019-02-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='last_update_timne',
            new_name='last_update_time',
        ),
    ]
